import { StyleSheet } from 'react-native';
export const driverColors = {
  cream: '#faf9f1',
  green: '#124f37',
  navy: '#111c2c',
  muted: '#78818a',
  border: '#e9e9df',
  mint: '#dcf0dd',
};
export const styles = StyleSheet.create({
  root: { flex: 1, width: '100%', backgroundColor: '#faf9f1' },
  top: {
    minHeight: 63,
    paddingHorizontal: 18,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderBottomWidth: 1,
    borderColor: '#e9e9df',
    backgroundColor: '#fffef8',
  },
  topTitle: {
    color: '#111c2c',
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'DriverBold',
  },
  badge: {
    borderRadius: 18,
    backgroundColor: '#dcf0dd',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 11,
    paddingVertical: 5,
  },
  badgeText: { color: '#124f37', fontSize: 12 },
  dot: { width: 7, height: 7, borderRadius: 5, backgroundColor: '#14a44d' },
  content: {
    padding: 18,
    gap: 14,
    width: '100%',
    maxWidth: 1060,
    alignSelf: 'center',
    paddingBottom: 24,
  },
  font: { fontFamily: 'DriverRegular', color: '#111c2c', fontSize: 15 },
  bold: { fontFamily: 'DriverBold', fontWeight: '700' },
  title: {
    fontFamily: 'DriverBold',
    color: '#111c2c',
    fontSize: 20,
    marginBottom: 4,
  },
  muted: {
    fontFamily: 'DriverRegular',
    color: '#78818a',
    fontSize: 13,
    lineHeight: 18,
  },
  row: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  spread: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  card: {
    backgroundColor: '#fffef9',
    borderWidth: 1,
    borderColor: '#e9e9df',
    borderRadius: 12,
    padding: 15,
    gap: 8,
  },
  hero: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    minHeight: 85,
    position: 'relative',
    overflow: 'hidden',
    borderRadius: 12,
    padding: 12,
  },
  metricRow: { flexDirection: 'row', gap: 8 },
  metric: {
    flex: 1,
    backgroundColor: '#fffef9',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e9e9df',
    padding: 10,
    gap: 5,
  },
  metricValue: { fontSize: 25, fontFamily: 'DriverBold', color: '#111c2c' },
  iconTile: {
    width: 36,
    height: 36,
    backgroundColor: '#eef1e5',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
  },
  greenButton: {
    backgroundColor: '#124f37',
    minHeight: 43,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  whiteButton: {
    backgroundColor: '#fffef9',
    minHeight: 40,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#dfe3d6',
    padding: 10,
    flexDirection: 'row',
    gap: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonText: { color: '#fff', fontFamily: 'DriverBold', fontSize: 15 },
  quickGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  quick: {
    flexGrow: 1,
    flexBasis: '45%',
    padding: 10,
    minHeight: 59,
    borderWidth: 1,
    borderColor: '#e9e9df',
    backgroundColor: '#fffef9',
    borderRadius: 9,
    flexDirection: 'row',
    gap: 9,
    alignItems: 'center',
  },
  tabs: {
    flexDirection: 'row',
    paddingTop: 8,
    paddingBottom: 8,
    backgroundColor: '#fffef8',
    borderTopWidth: 1,
    borderColor: '#e9e9df',
  },
  tab: {
    flex: 1,
    alignItems: 'center',
    gap: 3,
    minHeight: 48,
    justifyContent: 'center',
  },
  tabLabel: { fontSize: 11, color: '#78818a' },
  activeLabel: { color: '#124f37', fontFamily: 'DriverBold' },
  chip: {
    borderWidth: 1,
    borderColor: '#e9e9df',
    borderRadius: 20,
    paddingHorizontal: 13,
    paddingVertical: 6,
    backgroundColor: '#fffef9',
  },
  chipActive: { backgroundColor: '#124f37', borderColor: '#124f37' },
  chipText: { color: '#78818a', fontSize: 12 },
  checklistRow: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
    paddingVertical: 13,
    borderBottomWidth: 1,
    borderColor: '#eeeee4',
  },
  checkCircle: {
    width: 25,
    height: 25,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#cbd2c1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkDone: { backgroundColor: '#147843', borderColor: '#147843' },
  alert: {
    padding: 12,
    borderRadius: 9,
    backgroundColor: '#fff0dc',
    borderWidth: 1,
    borderColor: '#efdcba',
  },
  detailColumns: { flexDirection: 'row', flexWrap: 'wrap', gap: 15 },
  detailColumn: { flexGrow: 1, flexBasis: '45%', gap: 14 },
  reportType: {
    flexBasis: '30%',
    flexGrow: 1,
    minHeight: 70,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e2e5d9',
    padding: 10,
    gap: 5,
    backgroundColor: '#fffef9',
  },
  field: {
    backgroundColor: '#fffef9',
    borderWidth: 1,
    borderColor: '#d9decf',
    borderRadius: 8,
    padding: 12,
    color: '#111c2c',
    fontFamily: 'DriverRegular',
    fontSize: 15,
    minHeight: 110,
    textAlignVertical: 'top',
  },
  module: { flex: 1, minHeight: 0 },
  map: { height: 330, width: '100%', overflow: 'hidden', borderRadius: 12 },
});

// Exclusivo del conductor: no altera los paneles de otros roles.
export const conductorModuleStyles = StyleSheet.create({
  page: {
    width: '100%',
    maxWidth: 1060,
    alignSelf: 'center',
    padding: 18,
    gap: 12,
    paddingBottom: 24,
  },
  title: { color: '#111c2c', fontFamily: 'DriverBold', fontSize: 21 },
  cardTitle: { color: '#111c2c', fontFamily: 'DriverBold', fontSize: 17 },
  muted: {
    fontFamily: 'DriverRegular',
    color: '#78818a',
    fontSize: 13,
    lineHeight: 18,
  },
  label: { color: '#111c2c', fontFamily: 'DriverBold', fontSize: 14 },
  fullCard: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#e9e9df',
    borderRadius: 12,
    padding: 14,
    backgroundColor: '#fffef9',
    gap: 8,
  },
  card: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#e9e9df',
    borderRadius: 12,
    padding: 14,
    backgroundColor: '#fffef9',
    gap: 8,
  },
  grid: { width: '100%', gap: 10 },
  primary: {
    minHeight: 43,
    borderRadius: 8,
    backgroundColor: '#124f37',
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryText: { color: '#fff', fontFamily: 'DriverBold', fontSize: 15 },
  role: {
    backgroundColor: '#f1f1e7',
    borderWidth: 1,
    borderColor: '#e3e6db',
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderRadius: 19,
  },
  roleActive: { backgroundColor: '#dcf0dd', borderColor: '#3c985a' },
});
