import { StyleSheet } from 'react-native';
export const driverColors = {
  cream: '#fafbf9',
  green: '#064c3b',
  navy: '#0b2639',
  muted: '#78818a',
  border: '#e0e7e9',
  mint: '#dcf0dd',
};
export const styles = StyleSheet.create({
  root: { flex: 1, width: '100%', backgroundColor: '#fafbf9' },
  top: {
    minHeight: 63,
    paddingHorizontal: 18,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderBottomWidth: 1,
    borderColor: '#e0e7e9',
    backgroundColor: '#fcfdfb',
  },
  topTitle: {
    color: '#0b2639',
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'DriverBold',
  },
  badge: {
    borderRadius: 18,
    backgroundColor: '#dcf0dd',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 11,
    paddingVertical: 5,
  },
  badgeText: { color: '#064c3b', fontSize: 12 },
  dot: { width: 7, height: 7, borderRadius: 5, backgroundColor: '#14a44d' },
  content: {
    padding: 18,
    gap: 14,
    width: '100%',
    maxWidth: 1500,
    alignSelf: 'center',
    paddingBottom: 24,
  },
  font: { fontFamily: 'DriverRegular', color: '#0b2639', fontSize: 15 },
  darkFont: { color: '#edf6ef' },
  bold: { fontFamily: 'DriverBold', fontWeight: '700' },
  title: {
    fontFamily: 'DriverBold',
    color: '#0b2639',
    fontSize: 20,
    marginBottom: 4,
  },
  muted: {
    fontFamily: 'DriverRegular',
    color: '#78818a',
    fontSize: 13,
    lineHeight: 18,
  },
  row: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  spread: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  card: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e0e7e9',
    borderRadius: 12,
    padding: 15,
    gap: 8,
    height: 'max-content',
  },

  hero: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    minHeight: 85,
    position: 'relative',
    overflow: 'hidden',
    borderRadius: 12,
    padding: 12,
  },
  metricRow: { flexDirection: 'row', gap: 8 },
  metric: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e0e7e9',
    padding: 10,
    gap: 5,
  },
  metricValue: { fontSize: 25, fontFamily: 'DriverBold', color: '#0b2639' },
  iconTile: {
    width: 36,
    height: 36,
    backgroundColor: '#eef1e5',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
  },
  greenButton: {
    backgroundColor: '#064c3b',
    minHeight: 43,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  whiteButton: {
    backgroundColor: '#ffffff',
    minHeight: 40,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#dfe3d6',
    padding: 10,
    flexDirection: 'row',
    gap: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonText: { color: '#fff', fontFamily: 'DriverBold', fontSize: 15 },
  quickGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  quick: {
    flexGrow: 1,
    flexBasis: '45%',
    padding: 10,
    minHeight: 59,
    borderWidth: 1,
    borderColor: '#e0e7e9',
    backgroundColor: '#ffffff',
    borderRadius: 9,
    flexDirection: 'row',
    gap: 9,
    alignItems: 'center',
  },
  tabs: {
    flexDirection: 'row',
    paddingTop: 8,
    paddingBottom: 8,
    backgroundColor: '#fcfdfb',
    borderTopWidth: 1,
    borderColor: '#e0e7e9',
  },
  tab: {
    flex: 1,
    alignItems: 'center',
    gap: 3,
    minHeight: 48,
    justifyContent: 'center',
  },
  tabLabel: { fontSize: 11, color: '#78818a' },
  activeLabel: { color: '#064c3b', fontFamily: 'DriverBold' },
  chip: {
    borderWidth: 1,
    borderColor: '#e0e7e9',
    borderRadius: 20,
    paddingHorizontal: 13,
    paddingVertical: 6,
    backgroundColor: '#ffffff',
  },
  chipActive: { backgroundColor: '#064c3b', borderColor: '#064c3b' },
  chipText: { color: '#78818a', fontSize: 12 },
  checklistRow: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
    paddingVertical: 13,
    borderBottomWidth: 1,
    borderColor: '#eeeee4',
  },
  checkCircle: {
    width: 25,
    height: 25,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#cbd2c1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkDone: { backgroundColor: '#147843', borderColor: '#147843' },
  alert: {
    padding: 12,
    borderRadius: 9,
    backgroundColor: '#fff0dc',
    borderWidth: 1,
    borderColor: '#efdcba',
  },
  detailColumns: { flexDirection: 'row', flexWrap: 'wrap', gap: 15 },
  detailColumn: { flexGrow: 1, flexBasis: '45%', gap: 14 },
  reportType: {
    flexBasis: '30%',
    flexGrow: 1,
    minHeight: 70,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e2e5d9',
    padding: 10,
    gap: 5,
    backgroundColor: '#ffffff',
  },
  field: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#d9decf',
    borderRadius: 8,
    padding: 12,
    color: '#0b2639',
    fontFamily: 'DriverRegular',
    fontSize: 15,
    minHeight: 110,
    textAlignVertical: 'top',
  },
  module: { flex: 1, minHeight: 0 },
  darkRoot: { backgroundColor: '#102c27' },
  darkCard: { backgroundColor: '#17382f', borderColor: '#34594f' },
  darkBorder: { borderColor: '#34594f' },
  preferenceRow: { minHeight: 54, borderBottomWidth: 1, borderColor: '#e0e7e9', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  preferenceSwitch: { width: 38, height: 22, borderRadius: 14, backgroundColor: '#bdcbd0', padding: 3, justifyContent: 'center' },
  preferenceSwitchOn: { backgroundColor: '#087b60' },
  preferenceKnob: { width: 16, height: 16, borderRadius: 9, backgroundColor: '#fff', alignSelf: 'flex-start' },
  preferenceKnobOn: { alignSelf: 'flex-end' },
  map: { height: 330, width: '100%', overflow: 'hidden', borderRadius: 12 },
});

// Exclusivo del conductor: no altera los paneles de otros roles.
export const conductorModuleStyles = StyleSheet.create({
  page: {
    width: '100%',
    maxWidth: 1060,
    alignSelf: 'center',
    padding: 18,
    gap: 12,
    paddingBottom: 24,
  },
  title: { color: '#0b2639', fontFamily: 'DriverBold', fontSize: 21 },
  cardTitle: { color: '#0b2639', fontFamily: 'DriverBold', fontSize: 17 },
  muted: {
    fontFamily: 'DriverRegular',
    color: '#78818a',
    fontSize: 13,
    lineHeight: 18,
  },
  label: { color: '#0b2639', fontFamily: 'DriverBold', fontSize: 14 },
  fullCard: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#e0e7e9',
    borderRadius: 12,
    padding: 14,
    backgroundColor: '#ffffff',
    gap: 8,
  },
  card: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#e0e7e9',
    borderRadius: 12,
    padding: 14,
    backgroundColor: '#ffffff',
    gap: 8,
  },
  grid: { width: '100%', gap: 10 },
  primary: {
    minHeight: 43,
    borderRadius: 8,
    backgroundColor: '#064c3b',
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryText: { color: '#fff', fontFamily: 'DriverBold', fontSize: 15 },
  role: {
    backgroundColor: '#f1f1e7',
    borderWidth: 1,
    borderColor: '#e3e6db',
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderRadius: 19,
  },
  roleActive: { backgroundColor: '#dcf0dd', borderColor: '#3c985a' },
});
