import { StatusBar } from 'expo-status-bar';
import { useState } from 'react';
import { Image, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { API_BASE_URL } from './src/config';
import FarmerDashboard from './src/FarmerDashboard';
import FarmerTracking from './src/FarmerTracking';
import UserManagement from './src/UserManagement';
import CollectionRequestList from './src/CollectionRequestList';
import logo from './assets/brand/logo.png';

const colors={cream:'#DCE8B4',lime:'#A7C957',green:'#6A994E',forest:'#386641',white:'#fffdf7'};
let sessionToken='';
const Field=({label,value,onChangeText,secureTextEntry=false})=><View><Text style={styles.label}>{label}</Text><TextInput style={styles.input} value={value} onChangeText={onChangeText} secureTextEntry={secureTextEntry} placeholder={label}/></View>;
function Header({user,onLogout}){return <View style={styles.header}><Image source={logo} style={styles.logo}/><Text style={styles.brand}>COFFEE FLY</Text>{user?<TouchableOpacity onPress={onLogout}><Text style={styles.headerButton}>Salir</Text></TouchableOpacity>:<View/>}</View>}
function Login({onLogin}){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');const submit=async()=>{try{const r=await fetch(`${API_BASE_URL}/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw Error(d.detail||'No se pudo iniciar sesión');onLogin(d.user,d.access_token)}catch(e){setError(e.message)}};return <View style={styles.page}><Text style={styles.title}>Bienvenido</Text><Field label="Correo electrónico" value={email} onChangeText={setEmail}/><Field label="Contraseña" value={password} onChangeText={setPassword} secureTextEntry/><Text style={styles.error}>{error}</Text><TouchableOpacity style={styles.primary} onPress={submit}><Text style={styles.primaryText}>Iniciar sesión</Text></TouchableOpacity></View>}
function Dashboard({user,go}){const role=String(user.rol||'').toLowerCase();const caf=role==='caficultor';const cards=caf?[['Solicitar recolección','request'],['Mi actividad','farmerDashboard'],['Seguimiento de vehículo','tracking']]:role==='registrador'?[['Usuarios','users']]:role==='coordinador'?[['Solicitudes','requests']]:[];return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>Panel del {role}</Text><Text style={styles.muted}>Hola, {user.nombre}.</Text>{cards.map(([name,action])=><TouchableOpacity key={action} style={styles.card} onPress={()=>go(action)}><Text style={styles.cardTitle}>{name}</Text><Text style={styles.cardLink}>Abrir módulo</Text></TouchableOpacity>)}</ScrollView>}
function Request({user,go}){const[kg,setKg]=useState('');const[obs,setObs]=useState('');const[message,setMessage]=useState('');const submit=async()=>{try{const carga=await fetch(`${API_BASE_URL}/cargas/`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${sessionToken}`},body:JSON.stringify({peso_kg:Number(kg),descripcion:obs})});const c=await carga.json();if(!carga.ok)throw Error(c.detail||'No se pudo crear carga');const r=await fetch(`${API_BASE_URL}/solicitudes/`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${sessionToken}`},body:JSON.stringify({estado_solicitud:'pendiente',fecha_hora_solicitud:new Date().toISOString(),carga_id:c.id_carga})});if(!r.ok)throw Error('No se pudo crear solicitud');setMessage('Solicitud enviada correctamente')}catch(e){setMessage(e.message)}};return <View style={styles.page}><Text style={styles.title}>Solicitar recolección</Text><Field label="Cantidad de café (kg)" value={kg} onChangeText={setKg}/><Field label="Observaciones" value={obs} onChangeText={setObs}/><Text style={styles.muted}>{message}</Text><TouchableOpacity style={styles.primary} onPress={submit}><Text style={styles.primaryText}>Enviar solicitud</Text></TouchableOpacity><TouchableOpacity onPress={()=>go('dashboard')}><Text style={styles.link}>Volver</Text></TouchableOpacity></View>}
export default function App(){const[screen,setScreen]=useState('login');const[user,setUser]=useState(null);const login=(u,t)=>{sessionToken=t;setUser(u);setScreen('dashboard')};const logout=()=>{sessionToken='';setUser(null);setScreen('login')};const content=screen==='login'?<Login onLogin={login}/>:screen==='tracking'?<FarmerTracking go={setScreen} token={sessionToken} styles={styles}/>:screen==='farmerDashboard'?<FarmerDashboard go={setScreen} token={sessionToken} styles={styles}/>:screen==='request'?<Request user={user} go={setScreen}/>:screen==='users'?<UserManagement go={setScreen} token={sessionToken} styles={styles}/>:screen==='requests'?<CollectionRequestList go={setScreen} token={sessionToken} styles={styles}/>:<Dashboard user={user} go={setScreen}/>;return <SafeAreaView style={styles.safe}><Header user={user} onLogout={logout}/>{content}<StatusBar style="light"/></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.cream},header:{height:76,backgroundColor:colors.forest,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:18},logo:{width:52,height:52,resizeMode:'contain'},brand:{color:'#fff',fontWeight:'800',letterSpacing:2,fontSize:20},headerButton:{backgroundColor:colors.lime,color:colors.forest,fontWeight:'700',paddingHorizontal:12,paddingVertical:8,borderRadius:20},page:{padding:20,gap:14},title:{fontSize:26,fontWeight:'800',color:colors.forest},section:{fontSize:22,fontWeight:'800',color:colors.forest},label:{fontWeight:'700',color:colors.forest},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'rgba(56,102,65,.28)',borderRadius:9,padding:13,fontSize:16},primary:{backgroundColor:colors.forest,padding:14,borderRadius:9,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'800',fontSize:16},link:{color:colors.forest,fontWeight:'800',textAlign:'center'},error:{color:'#b42318',fontWeight:'700'},muted:{color:'#526451',fontSize:16,lineHeight:23},card:{backgroundColor:colors.white,borderRadius:14,padding:18,gap:7,shadowColor:'#000',shadowOpacity:.08,shadowRadius:7,elevation:2},cardTitle:{fontSize:18,fontWeight:'800',color:colors.forest},cardLink:{color:colors.green,fontWeight:'800'}});
