import { colores } from '../colores';

export const estilosEstructura = {
  safe: { flex: 1, backgroundColor: colores.crema },
  header: { minHeight: 76, backgroundColor: colores.bosque, paddingHorizontal: 18, paddingVertical: 10, borderBottomWidth: 3, borderBottomColor: colores.lima },
  headerInner: { width: '100%', maxWidth: 1180, alignSelf: 'center', flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  brandGroup: { flexDirection: 'row', alignItems: 'center', gap: 10, minWidth: 180 },
  logo: { width: 46, height: 46, resizeMode: 'contain' },
  brand: { color: '#fff', fontWeight: '700', letterSpacing: 2, fontSize: 18 },
  headerContext: { color: colores.crema, fontSize: 12, lineHeight: 16, fontWeight: '700' },
  headerActions: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'flex-end', gap: 8 },
  backButton: { minHeight: 44, borderWidth: 1, borderColor: 'rgba(255,255,255,.45)', borderRadius: 9, paddingHorizontal: 13, alignItems: 'center', justifyContent: 'center' },
  backButtonText: { color: '#fff', fontWeight: '700' },
  userBadge: { paddingHorizontal: 11, paddingVertical: 5, borderLeftWidth: 1, borderLeftColor: 'rgba(255,255,255,.28)' },
  userName: { color: '#fff', fontWeight: '700', fontSize: 13 },
  userRole: { color: colores.crema, fontSize: 11, lineHeight: 15, textTransform: 'capitalize' },
  headerButton: { backgroundColor: colores.lima, color: colores.bosque, fontWeight: '700', paddingHorizontal: 15, paddingVertical: 10, borderRadius: 9, overflow: 'hidden' },
  connectionBanner: { backgroundColor: '#EAF2EC', borderBottomWidth: 1, borderColor: 'rgba(56,102,65,.2)', paddingHorizontal: 18, paddingVertical: 7 },
  connectionText: { color: colores.bosque, fontSize: 13, lineHeight: 18, fontWeight: '700', maxWidth: 1180, width: '100%', alignSelf: 'center' },
  screenStage: { flex: 1, position: 'relative', overflow: 'hidden', backgroundColor: colores.crema },
  screenContent: { flex: 1, minWidth: 0, minHeight: 0, zIndex: 1 },
  page: { width: '100%', maxWidth: 1180, alignSelf: 'center', paddingHorizontal: 24, paddingTop: 28, paddingBottom: 48, gap: 20 },
  content: { width: '100%', maxWidth: 740, alignSelf: 'center', gap: 14 },
  title: { fontSize: 28, lineHeight: 36, fontWeight: '700', color: colores.bosque, letterSpacing: -0.5 },
  section: { fontSize: 20, lineHeight: 27, fontWeight: '700', color: colores.bosque, marginTop: 14, paddingBottom: 7, borderBottomWidth: 1, borderBottomColor: 'rgba(56,102,65,.2)' },
  pageMuted: { color: '#526451', fontSize: 14, lineHeight: 21 },
  pageLabel: { fontSize: 14, lineHeight: 19, fontWeight: '700', color: colores.bosque, marginBottom: 5 },
  grid: { width: '100%', flexDirection: 'row', flexWrap: 'wrap', alignItems: 'stretch', gap: 14 },
};
