export const coordinatorModuleStyles = {
  page: {
    width: '100%',
    alignSelf: 'center',
    padding: 0,
    gap: 14,
    paddingBottom: 24,
  },
  title: { color: '#102c3c', fontSize: 26, fontWeight: '700' },
  section: { color: '#102c3c', fontSize: 18, fontWeight: '700', marginTop: 7 },
  cardTitle: { color: '#102c3c', fontSize: 18, fontWeight: '700' },
  muted: { color: '#63748a', fontSize: 14, lineHeight: 20 },
  card: {
    flexGrow: 1,
    flexBasis: 260,
    maxWidth: 440,
    minWidth: 0,
    backgroundColor: '#fff',
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#e2e9ec',
    padding: 16,
    gap: 8,
  },
  cardSelected: {
    borderColor: '#147253',
    borderWidth: 2,
    backgroundColor: '#edf7ef',
  },
  fullCard: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#e2e9ec',
    borderRadius: 9,
    backgroundColor: '#fff',
    padding: 16,
    gap: 8,
  },
  formCard: {
    width: '100%',
    maxWidth: '100%',
    borderWidth: 1,
    borderColor: '#e2e9ec',
    borderRadius: 9,
    backgroundColor: '#fff',
    padding: 18,
    gap: 12,
  },
  deliveryForm: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#e2e9ec',
    borderRadius: 9,
    backgroundColor: '#fff',
    padding: 18,
    gap: 12,
  },
  primary: {
    backgroundColor: '#075441',
    borderRadius: 6,
    paddingHorizontal: 17,
    paddingVertical: 10,
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deliverySubmit: {
    backgroundColor: '#075441',
    borderRadius: 6,
    padding: 12,
    alignItems: 'center',
  },
  primaryText: { color: '#fff', fontSize: 15, fontWeight: '700' },
  secondary: {
    borderWidth: 1,
    borderColor: '#cddcde',
    backgroundColor: '#fff',
    borderRadius: 6,
    minHeight: 38,
    padding: 10,
    alignItems: 'center',
  },
  secondaryText: { color: '#075441', fontSize: 14, fontWeight: '700' },
  input: {
    width: '100%',
    minHeight: 40,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#dce5e9',
    borderRadius: 6,
    padding: 10,
    fontSize: 15,
    color: '#17374b',
  },
  metric: {
    flexGrow: 1,
    flexBasis: 160,
    backgroundColor: '#edf7f1',
    borderWidth: 1,
    borderColor: '#e2e9ec',
    borderRadius: 8,
    padding: 14,
    gap: 5,
  },
  metricLabel: { color: '#557183', fontSize: 13 },
  metricValue: { color: '#102c3c', fontSize: 27, fontWeight: '700' },
};
