import { crearEstilosModulo } from '../../estilos/crearEstilosModulo';
import { StyleSheet } from 'react-native';

export const styles = crearEstilosModulo({
  mapCanvas: { flex: 1 },
  mapPanelCompact: { height: 300, padding: 0 },
  unavailable: { opacity: 0.55 },
  navigationBanner: { width: '100%', backgroundColor: '#17351f', borderRadius: 16, padding: 18, gap: 5 },
  navigationEyebrow: { color: '#b7d8ad', fontSize: 11, fontWeight: '800', letterSpacing: 1 },
  navigationInstruction: { color: '#ffffff', fontSize: 22, fontWeight: '800', lineHeight: 28 },
  navigationMeta: { color: '#e2f0df', fontSize: 15, fontWeight: '600' },
  navigationTraffic: { color: '#b7c5b7', fontSize: 12 },
  navigationRetry: { alignSelf: 'flex-start', marginTop: 6, paddingVertical: 8, paddingHorizontal: 12, borderRadius: 9, backgroundColor: '#f3d58b' },
  navigationRetryText: { color: '#3f2e08', fontWeight: '800' },
  navigationScreen: { flex: 1, width: '100%', position: 'relative', overflow: 'hidden', backgroundColor: '#dfe7e2' },
  navigationMap: { ...StyleSheet.absoluteFillObject },
  navigationTop: { position: 'absolute', top: 10, left: 10, right: 78, alignItems: 'flex-start' },
  turnCard: { width: '100%', minHeight: 86, flexDirection: 'row', alignItems: 'center', backgroundColor: '#075f5b', borderRadius: 18, paddingHorizontal: 14, paddingVertical: 10, elevation: 10, shadowColor: '#000', shadowOpacity: .2, shadowRadius: 10 },
  turnIcon: { width: 48, color: '#fff', fontSize: 40, lineHeight: 46, fontWeight: '600', textAlign: 'center' },
  turnCopy: { flex: 1, paddingLeft: 10 },
  turnDistance: { color: '#bde5df', fontSize: 13, fontWeight: '800' },
  turnText: { color: '#fff', fontSize: 19, lineHeight: 23, fontWeight: '900' },
  nextTurnCard: { backgroundColor: '#064b49', marginLeft: 12, paddingHorizontal: 14, paddingVertical: 7, borderBottomLeftRadius: 13, borderBottomRightRadius: 13, maxWidth: '90%' },
  nextTurnText: { color: '#fff', fontSize: 13, fontWeight: '800' },
  currentRoadPill: { position: 'absolute', left: 12, top: 125, maxWidth: '64%', backgroundColor: 'rgba(255,255,255,.96)', borderRadius: 12, paddingHorizontal: 11, paddingVertical: 7, elevation: 6 },
  currentRoadLabel: { color: '#68766d', fontSize: 9, fontWeight: '900', letterSpacing: 1 },
  currentRoadText: { color: '#16351f', fontSize: 16, fontWeight: '900' },
  gpsQualityText: { color: '#53685a', fontSize: 10, fontWeight: '700', marginTop: 2 },
  navigationControls: { position: 'absolute', right: 12, top: 104, gap: 8 },
  roundControl: { width: 54, height: 54, borderRadius: 27, backgroundColor: 'rgba(255,255,255,.96)', alignItems: 'center', justifyContent: 'center', elevation: 7, borderWidth: 1, borderColor: 'rgba(15,35,22,.12)' },
  roundControlActive: { borderWidth: 3, borderColor: '#07847c' },
  roundControlText: { color: '#17351f', fontSize: 11, fontWeight: '900' },
  navigationBottom: { position: 'absolute', left: 10, right: 10, bottom: 10, backgroundColor: 'rgba(255,255,255,.97)', borderRadius: 18, padding: 11, elevation: 12, shadowColor: '#000', shadowOpacity: .18, shadowRadius: 12, gap: 7 },
  tripSummary: { alignItems: 'center' },
  tripTime: { color: '#c0392b', fontSize: 24, lineHeight: 28, fontWeight: '900' },
  tripMeta: { color: '#526451', fontSize: 12, fontWeight: '700' },
  tripDestination: { color: '#17351f', fontSize: 12, marginTop: 1, maxWidth: '95%' },
  navigationAction: { minHeight: 42, borderRadius: 11, backgroundColor: '#17351f', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 14 },
  navigationActionText: { color: '#fff', fontSize: 15, fontWeight: '900' },
  navigationError: { color: '#a02b1f', fontSize: 12, textAlign: 'center' },
});
