import {canAdvanceGpsInstruction,canConfirmDriverPickup,compactDistance,distanceCoordinates,gpsStop,turnIcon} from '../src/modulos/conductor/presentacionGps';
describe('presentación GPS del conductor',()=>{
  test('la recogida requiere señal fiable, cercanía y etapa correcta',()=>{const point={latitud:5,longitud:-75,precision_m:5,registrada_en:new Date().toISOString()};const tracking={etapa_viaje:'hacia_finca',destino_latitud:5,destino_longitud:-75};expect(canConfirmDriverPickup(tracking,point)).toBe(true);expect(canConfirmDriverPickup({...tracking,etapa_viaje:'hacia_cooperativa'},point)).toBe(false);expect(canConfirmDriverPickup({...tracking,carga_recogida_en:'2026-09-16'},point)).toBe(false);expect(canConfirmDriverPickup({...tracking,destino_latitud:6},point)).toBe(false);expect(canConfirmDriverPickup(tracking,{...point,precision_m:79})).toBe(false);});
  test('muestra unidades cortas sin inventar distancias ausentes',()=>{expect(compactDistance(300)).toBe('300 m');expect(compactDistance(11000)).toBe('11.0 km');expect(compactDistance(null)).toBe('—');});
  test('selecciona símbolos según las indicaciones reales',()=>{expect(turnIcon('Gira a la derecha')).toBe('turnRight');expect(turnIcon('Gira a la izquierda')).toBe('turnLeft');expect(turnIcon('Continúa recto')).toBe('straight');expect(turnIcon('En la glorieta toma la salida')).toBe('roundabout');});
  test('no confunde una finca con la parada final de cooperativa',()=>{const trip={cargas:[{id_entrega:'a'},{id_entrega:'b'},{id_entrega:'c'}]};expect(gpsStop(trip,'b','hacia_finca')).toMatchObject({number:2,total:4,cooperative:false});expect(gpsStop(trip,'c','hacia_cooperativa')).toMatchObject({number:4,total:4,cooperative:true});expect(gpsStop(trip,'missing','hacia_finca').number).toBeNull();});
  test('mide cercanía geográfica y rechaza coordenadas ausentes',()=>{expect(distanceCoordinates({latitude:5,longitude:-75},{latitude:5,longitude:-75})).toBe(0);expect(distanceCoordinates(null,{latitude:5,longitude:-75})).toBeNull();expect(distanceCoordinates({latitude:null,longitude:-75},{latitude:5,longitude:-75})).toBeNull();});
  test('no avanza giros con señal imprecisa, antigua o futura',()=>{const point={latitud:5,longitud:-75,precision_m:5,registrada_en:new Date().toISOString()};expect(canAdvanceGpsInstruction(point)).toBe(true);for(const change of [{precision_m:79},{precision_m:-1},{precision_m:null},{latitud:200},{registrada_en:new Date(Date.now()-100000).toISOString()},{registrada_en:new Date(Date.now()+20000).toISOString()}])expect(canAdvanceGpsInstruction({...point,...change})).toBe(false);});
});
