import { crearEstilosModulo } from '../../estilos/crearEstilosModulo';

export const styles = crearEstilosModulo({
  dashboardIntro: { backgroundColor: '#E8F2EB', borderRadius: 16, borderWidth: 1, borderColor: '#D2E4D7', padding: 24, gap: 8 },
  dashboardEyebrow: { color: '#287457', fontSize: 12, lineHeight: 17, fontWeight: '700', letterSpacing: 1.2, textTransform: 'uppercase' },
  dashboardStatus: { marginTop: 2 },
  actionCard: { minHeight: 194, justifyContent: 'space-between' },
  actionTop: { gap: 9 },
  actionIcon: { width: 38, height: 38, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: '#EEF4D5' },
  actionIconText: { color: '#386641', fontSize: 20, fontWeight: '900' },
  actionDescription: { color: '#526451', fontSize: 14, lineHeight: 21 },
  actionLinkRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 5 },
  actionArrow: { color: '#6A994E', fontSize: 20, fontWeight: '900' },
  refreshButton: { alignSelf: 'flex-start', minWidth: 190 },
  secondary: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#B7CBBE', borderRadius: 10, minHeight: 48, paddingHorizontal: 18, paddingVertical: 12, alignItems: 'center', justifyContent: 'center' },
  secondaryText: { color: '#123F34', fontWeight: '700', textAlign: 'center' },
  darkPage: { backgroundColor: '#102c27' },
  compactPage: { paddingVertical: 10, gap: 8 },
  darkText: { color: '#edf6ef' },
  darkMuted: { color: '#c5ddd0' },
  darkCard: { backgroundColor: '#17382f', borderColor: '#34594f' },
  preferenceCard: { borderWidth: 1, borderColor: '#dfe7e1', borderRadius: 12, padding: 16, gap: 10, backgroundColor: '#fff' },
  preferenceRow: { minHeight: 50, borderBottomWidth: 1, borderColor: '#e0e7e9', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  preferenceSwitch: { width: 38, height: 22, borderRadius: 14, backgroundColor: '#bdcbd0', padding: 3, justifyContent: 'center' },
  preferenceSwitchOn: { backgroundColor: '#087b60' },
  preferenceKnob: { width: 16, height: 16, borderRadius: 9, backgroundColor: '#fff', alignSelf: 'flex-start' },
  preferenceKnobOn: { alignSelf: 'flex-end' },
});
