import { useState } from 'react';
import { Platform, ScrollView, Text, TextInput, TouchableOpacity, View } from 'react-native';
import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';

import { API_BASE_URL, fetchApi } from './config';

export default function Reports({ token, go, styles }) {
  const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [report, setReport] = useState(null); const [message, setMessage] = useState('');
  const query = () => { const value = new URLSearchParams(); if (from) value.set('fecha_desde', from); if (to) value.set('fecha_hasta', to); return value.toString(); };
  const generate = async () => { try { const response = await fetchApi(`${API_BASE_URL}/reportes/?${query()}`, { headers: { Authorization: `Bearer ${token}` } }); const data = await response.json(); if (!response.ok) throw Error(data.detail || 'No se pudo generar el reporte.'); setReport(data); setMessage('Reporte generado correctamente.'); } catch (error) { setMessage(error.message); } };
  const exportReport = async (format) => { try { const url = `${API_BASE_URL}/reportes/exportar?formato=${format}${query() ? `&${query()}` : ''}`; const extension = format === 'excel' ? 'xlsx' : 'pdf'; if (Platform.OS === 'web') { const response = await fetchApi(url, { headers: { Authorization: `Bearer ${token}` }, timeoutMs: 30000 }); if (!response.ok) { const data = await response.json(); throw Error(data.detail || 'No se pudo exportar el reporte.'); } const blob = await response.blob(); const href = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = href; anchor.download = `reporte_operaciones_${new Date().toISOString().slice(0, 10)}.${extension}`; anchor.click(); URL.revokeObjectURL(href); setMessage(`Descarga de ${format.toUpperCase()} iniciada.`); return; } const target = `${FileSystem.cacheDirectory}reporte_operaciones_${new Date().toISOString().slice(0, 10)}.${extension}`; const file = await FileSystem.downloadAsync(url, target, { headers: { Authorization: `Bearer ${token}` } }); if (!(await Sharing.isAvailableAsync())) throw Error('Compartir archivos no está disponible en este dispositivo.'); await Sharing.shareAsync(file.uri); setMessage(`Reporte ${format.toUpperCase()} listo para guardar o compartir.`); } catch (error) { setMessage(error.message); } };
  const section = (title, rows, fields) => <View style={styles.card}><Text style={styles.cardTitle}>{title}</Text>{rows?.length ? rows.map((row, index) => <Text key={index}>{fields.map((field) => row[field]).join(' · ')}</Text>) : <Text style={styles.muted}>Sin datos para el período.</Text>}</View>;
  return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>Reportes operativos</Text><Text style={styles.muted}>Genera reportes de máximo 30 días: café por caficultor, entregas por vehículo y resumen diario.</Text>{message ? <Text style={styles.success}>{message}</Text> : null}<View style={styles.card}><Text style={styles.label}>Desde (AAAA-MM-DD)</Text><TextInput style={styles.input} value={from} onChangeText={setFrom} placeholder="2026-08-01" /><Text style={styles.label}>Hasta (AAAA-MM-DD)</Text><TextInput style={styles.input} value={to} onChangeText={setTo} placeholder="2026-08-28" /><TouchableOpacity style={styles.primary} onPress={generate}><Text style={styles.primaryText}>Generar reporte</Text></TouchableOpacity></View>{report ? <><Text style={styles.muted}>Período: {String(report.periodo.desde)} a {String(report.periodo.hasta)}</Text>{section('Total de café por caficultor', report.cafe_por_caficultor, ['caficultor', 'kilogramos'])}{section('Entregas por vehículo', report.entregas_por_vehiculo, ['vehiculo', 'entregas', 'kilogramos'])}{section('Resumen diario', report.resumen_diario, ['fecha', 'entregas', 'kilogramos'])}<View style={styles.statusActions}><TouchableOpacity style={styles.primary} onPress={() => exportReport('pdf')}><Text style={styles.primaryText}>Exportar PDF</Text></TouchableOpacity><TouchableOpacity style={styles.primary} onPress={() => exportReport('excel')}><Text style={styles.primaryText}>Exportar Excel</Text></TouchableOpacity></View></> : null}<TouchableOpacity onPress={() => go('dashboard')}><Text style={styles.link}>Volver al dashboard</Text></TouchableOpacity></ScrollView>;
}
