import { Platform } from 'react-native';

import { crearEstilosModulo } from '../../estilos/crearEstilosModulo';

export const styles = crearEstilosModulo({
  loginPage: {
    flex: 1, backgroundColor: '#F7F8F3',
  },
  loginScroller: { flex: 1 },
  loginScroll: { flexGrow: 1 },
  loginLayout: { flex: 1, minHeight: Platform.OS === 'web' ? '100vh' : 760, flexDirection: 'row', backgroundColor: '#F7F8F3' },
  loginLayoutMobile: { flexDirection: 'column', minHeight: 820 },
  loginVisual: { width: '50%', minHeight: 720, position: 'relative', overflow: 'hidden' },
  loginVisualMobile: { width: '100%', height: 330, minHeight: 330 },
  loginVisualImage: { width: '100%', height: '100%' },
  loginVisualImageDesktop: Platform.OS === 'web' ? { objectPosition: 'center center' } : {},
  loginVisualImageMobile: Platform.OS === 'web' ? { objectPosition: '62% center' } : {},
  loginVisualShade: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, backgroundColor: 'rgba(4,37,30,.13)' },
  loginStory: { flex: 1, zIndex: 1, paddingHorizontal: 66, paddingTop: 46, paddingBottom: 146, justifyContent: 'space-between', maxWidth: 690 },
  loginBrand: { alignItems: 'center' },
  loginLogo: { width: 138, height: 88, marginBottom: -10 },
  loginBrandName: { color: '#063C31', fontSize: 37, lineHeight: 43, fontWeight: '900', letterSpacing: -1.4 },
  loginSlogan: { color: '#063C31', fontSize: 16, lineHeight: 21, fontWeight: '800' },
  loginStoryCopy: { marginTop: 38, maxWidth: 420 },
  loginStoryTitle: { color: '#FFFFFF', fontSize: 40, lineHeight: 45, fontWeight: '900', letterSpacing: -1 },
  loginStoryBody: { color: '#FFFFFF', fontSize: 17, lineHeight: 25, marginTop: 14, textShadowColor: 'rgba(0,0,0,.35)', textShadowRadius: 8 },
  loginBenefits: { gap: 17, marginVertical: 30 },
  loginBenefit: { color: '#FFFFFF', fontSize: 17, lineHeight: 23, fontWeight: '700', textShadowColor: 'rgba(0,0,0,.5)', textShadowRadius: 7 },
  loginMotto: { position: 'absolute', zIndex: 2, left: 66, bottom: 34, width: 245, transform: [{ rotate: '-5deg' }] },
  loginMottoMobile: { left: 27, top: 62, bottom: 'auto', width: 180 },
  loginMottoText: { color: '#FFF6DB', fontFamily: Platform.OS === 'web' ? 'Segoe Script, Brush Script MT, cursive' : Platform.OS === 'ios' ? 'Snell Roundhand' : 'cursive', fontSize: 34, lineHeight: 39, fontWeight: '600', textShadowColor: 'rgba(0,0,0,.6)', textShadowOffset: { width: 0, height: 2 }, textShadowRadius: 8 },
  loginMottoTextMobile: { fontSize: 27, lineHeight: 31 },
  loginMottoSecondLine: { marginLeft: 20, marginTop: -2 },
  loginMottoUnderline: { width: 150, height: 4, marginTop: 7, marginLeft: 33, borderRadius: 5, backgroundColor: '#FFF0C2', transform: [{ rotate: '-2deg' }], shadowColor: '#102D25', shadowOpacity: .25, shadowRadius: 3 },
  loginPanel: { width: '50%', minHeight: 720, paddingHorizontal: 42, paddingVertical: 34, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F9FAF6' },
  loginPanelMobile: { width: '100%', minHeight: 570, marginTop: -58, borderTopLeftRadius: 38, borderTopRightRadius: 38, paddingHorizontal: 15, paddingTop: 0, paddingBottom: 28, zIndex: 3, backgroundColor: 'transparent' },
  loginCard: {
    width: '100%', maxWidth: 540, paddingHorizontal: 38, paddingVertical: 28, borderRadius: 16,
    backgroundColor: 'rgba(255,255,252,.96)', borderWidth: 1, borderColor: 'rgba(31,61,52,.10)',
    shadowColor: '#15362C', shadowOpacity: .11, shadowRadius: 24, elevation: 8,
  },
  loginCardMobile: { maxWidth: 690, paddingHorizontal: 20, paddingTop: 23, paddingBottom: 25, borderRadius: 34 },
  loginTitle: { color: '#063C31', fontSize: 29, lineHeight: 35, fontWeight: '900', textAlign: 'center', marginTop: 18 },
  loginDescription: { color: '#5B6878', fontSize: 17, lineHeight: 24, textAlign: 'center', marginTop: 1, marginBottom: 20 },
  loginFields: { width: '100%', gap: 14 },
  loginInputShell: { width: '100%', minHeight: 68, borderWidth: 1, borderColor: '#D6DDE0', borderRadius: 11, flexDirection: 'row', backgroundColor: '#FFFFFF', overflow: 'hidden' },
  loginInputIcon: { width: 52, alignItems: 'center', justifyContent: 'center', borderRightWidth: 1, borderRightColor: '#EDF0F1' },
  loginInputIconText: { color: '#074638', fontSize: 23, lineHeight: 28, fontWeight: '500' },
  loginInputContent: { flex: 1, justifyContent: 'center', paddingLeft: 14, paddingRight: 8, paddingVertical: 8 },
  loginInputLabel: { color: '#16352F', fontSize: 13, lineHeight: 17, fontWeight: '700' },
  loginInput: { width: '100%', minHeight: 28, padding: 0, color: '#213B36', fontSize: 14, lineHeight: 20, borderWidth: 0, outlineStyle: 'none' },
  loginVisibilityButton: { position: 'absolute', right: 0, top: -16, bottom: -8, width: 50, alignItems: 'center', justifyContent: 'center' },
  loginEye: { width: 22, height: 15, borderWidth: 2, borderColor: '#506674', borderRadius: 13, alignItems: 'center', justifyContent: 'center' },
  loginEyePupil: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#506674' },
  loginEyeSlash: { position: 'absolute', width: 26, height: 2, backgroundColor: '#506674', transform: [{ rotate: '-42deg' }] },
  loginButton: { width: '100%', minHeight: 56, marginTop: 20, borderRadius: 10, paddingHorizontal: 22, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#087052', shadowColor: '#0C5A45', shadowOpacity: .14, shadowRadius: 8, elevation: 3 },
  loginButtonText: { color: '#FFFFFF', fontSize: 17, lineHeight: 22, fontWeight: '800' },
  loginButtonArrow: { position: 'absolute', right: '35%', color: '#FFFFFF', fontSize: 25, lineHeight: 29 },
  loginHelp: { color: '#607078', fontSize: 12, lineHeight: 18, textAlign: 'center', marginTop: 13 },
  loginTrustRow: { width: '100%', maxWidth: 590, flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: 22, marginTop: 28 },
  loginTrust: { color: '#52666B', fontSize: 12, lineHeight: 17, textAlign: 'center' },
  loginCopyright: { color: '#52666B', fontSize: 12, lineHeight: 17, marginTop: 23, textAlign: 'center' },
  loading: { opacity: 0.6 },
});
